<a href="https://colab.research.google.com/github/THSSIR18/cuny-mc-arrays/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
np_city = np.array(['New York City', 'Los Angeles', 'Miami', 'Houston'])
np_city

array(['New York City', 'Los Angeles', 'Miami', 'Houston'], dtype='<U13')

In [ ]:
np_city.ndim

1

In [ ]:
np_city_and_state = np.array([['New York City', 'Los Angeles', 'Miami', 'Houston'],
                             ['New York', 'California', 'Florida', 'Texas']])
np_city_and_state

array([['New York City', 'Los Angeles', 'Miami', 'Houston'],
       ['New York', 'California', 'Florida', 'Texas']], dtype='<U13')

In [ ]:
print('Dimension = ' + str(np_city.ndim))
print('Shape = ' + str(np_city.shape))
print('Size= ' + str(np_city.size))

Dimension = 1
Shape = (4,)
Size= 4


In [ ]:
print('Dimension = ' + str(np_city_and_state.ndim))
print('Shape = ' + str(np_city_and_state.shape))
print('Size= ' + str(np_city_and_state.size))

Dimension = 2
Shape = (2, 4)
Size= 8


In [ ]:
first_trial_cyclist = [10, 15,17,26]
second_trial_cyclist = [12,11,21,24]
np_first = np.array(first_trial_cyclist)
np_second = np.array(second_trial_cyclist)
print(np_first)
print(np_second)
total = np_first + np_second
print(total)

[10 15 17 26]
[12 11 21 24]
[22 26 38 50]


In [ ]:
cyclist_trials = np.array ([[10, 15,17,26],[12,11,21,24]])
first_trial = cyclist_trials[0]
first_trial



array([10, 15, 17, 26])

In [ ]:
second_trial = cyclist_trials[1]
second_trial[0]




12

In [ ]:
print(cyclist_trials)
print(cyclist_trials[1][2])

[[10 15 17 26]
 [12 11 21 24]]
21


In [ ]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
passing_scores = test_scores > 60
passing_scores[1][2]
print(passing_scores)
print(test_scores[passing_scores])

[[ True  True False  True]
 [False  True  True False]]
[83 71 63 68 81]


In [ ]:
boroughs_in_nyc = np.array(['Manhattan','Bronx','Brooklyn','Staten Island','Queens'])
print(boroughs_in_nyc)
boroughs_view = boroughs_in_nyc.view()
boroughs_view[3] = 'Central Park'
print(boroughs_view)
print(boroughs_in_nyc)

['Manhattan' 'Bronx' 'Brooklyn' 'Staten Island' 'Queens']
['Manhattan' 'Bronx' 'Brooklyn' 'Central Park' 'Queens']
['Manhattan' 'Bronx' 'Brooklyn' 'Central Park' 'Queens']


In [ ]:
boroughs_in_nyc = np.array(['Manhattan','Bronx','Brooklyn','Staten Island','Queens'])
boroughs_copy = boroughs_in_nyc.copy()
print(boroughs_copy)
print(boroughs_copy)

['Manhattan' 'Bronx' 'Brooklyn' 'Staten Island' 'Queens']
['Manhattan' 'Bronx' 'Brooklyn' 'Staten Island' 'Queens']


In [ ]:
np_sqrt = np.sqrt([4,9,16,25])
np_sqrt

array([2., 3., 4., 5.])

In [ ]:
from numpy import pi 
pi
np.cos(pi)

-1.0

In [ ]:
# floor returns largest integer of any value in the array
np.floor([1,5,2.6,7.8,-3,-2.3])

array([ 1.,  5.,  2.,  7., -3., -3.])

In [ ]:
# Exponential funtion 
ar = np.array([1,2,3])
ar=np.exp(ar)
print(ar)                                                                                                                                                                                                                                                                                                               

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a + b
print(c)

[11 22 33 44]


In [ ]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b=np.array([1,2,3])

print('First array:')
print(b)
print('\n')

print('Second array:')
print(a)
print('\n')

print('First array + Second array')
c=a+b
print(c)



First array:
[1 2 3]


Second array:
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


First array + Second array
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
#transpose
test_scores = np.array([[83,71,57,63],[54,69,81,45]])
test_scores

array([[83, 71, 57, 63],
       [54, 69, 81, 45]])

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.linalg.inv(x)
print(x)
print(y)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
trace_array=np.array([[1,4],[3,7]])
np.trace(trace_array)

8